---
computer_name: suzushiro
local_host_name: suzushiro
karabiner:
#  source_private_xml: '{{ dotfiles.dest }}/osx/keyremap4macbook/private.xml'
#  config_dir: "{{ ansible_env.HOME }}/Library/Application Support/Karabiner"
  command: /Applications/Karabiner.app/Contents/Library/bin/karabiner
  config:
    -
      name: remap.jis_yen2backslash
      value: 1
    -
      name: remap.forwarddelete2delete
      value: 1
    -
      name: repeat.initial_wait
      value: 100
    -
      name: repeat.wait
      value: 20
homebrew:
  repo: git://github.com/homebrew/Homebrew.git
  dest: /Users/yohei/local/homebrew
  packages:
    -
      name:  ack
    -
      name:  ctags
    -
      name:  curl
    -
      name:  docker
    -
      name:  git
    -
      name:  gmp
    -
      name:  go
      install_options: --cross-compile-common
    -
      name:  httpie
    -
      name:  hub
    -
      name:  imagemagick
    -
      name:  jq
    -
      name:  leiningen
    -
      name:  libpng
    -
      name:  lua
    -
      name:  lv
    -
      name:  memcached
    -
      name:  mercurial
    -
      name:  mongodb
    -
      name:  mysql55
    -
      name:  nginx
    -
      name:  node
    -
      name:  postgresql
    -
      name:  proxychains-ng
    -
      name:  readline
    -
      name:  reattach-to-user-namespace
      install_options: --with-launchctl --with-pbcopy-and-pbpaste
    -
      name:  redis
    -
      name:  sbt
    -
      name:  sqlite
    -
      name:  terminal-notifier
    -
      name:  tig
    -
      name:  tmux
    -
      name:  tree
    -
      name:  wget
    -
      name:  zsh
      install_options: --disable-etcdir
#osx_apps:
#  casks:
#    - name: alfred
#    - name: dropbox
#    - name: karabiner
#    - name: xquartz
#    - name: virtualbox
#    - name: boot2docker
#    - name: caskroom/versions/iterm2-beta
#    - name: caskroom/versions/macvim-kaoriya
ruby_versions:
  - version: 2.2.0
perl_versions:
  - version: 5.20.1
dotfiles:
  dest: ~/working/github.com/hakobe/dotfiles
  repo: git://github.com/hakobe/dotfiles.git
