---
-
  name: Install plenv
  homebrew:
    name: plenv
-
  name: Install perl-build
  homebrew:
      name: perl-build
-
  name: Install Perls
  command: "{{ homebrew.dest }}/bin/plenv install {{ item.version }}"
  args:
    creates: "{{ homebrew.dest }}/versions/{{ item.version }}"
  with_items: perl_versions
